-- Stage 1
INSERT INTO Stage (id, status) VALUES (1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (1, 0, 0, 7, 9, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (1, 1, 0, 2, 5, 2, 1, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (1, 2, 1, 0, 5, 0, 0, 1);

-- Stage 2
INSERT INTO Stage (id, status) VALUES (2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (2, 0, 0, 5, 7, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (2, 1, 0, 10, 7, 2, 4, 6);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (2, 2, 0, 1, 5, 2, 1, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (2, 3, 0, 4, 4, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (2, 4, 1, 0, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (2, 5, 1, 1, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (2, 6, 1, 2, 5, 0, 0, 1);

-- Stage 3
INSERT INTO Stage (id, status) VALUES (3, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (3, 0, 0, 5, 9, 1, 3, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (3, 1, 0, 0, 8, 2, 4, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (3, 2, 0, 7, 7, 1, 6, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (3, 3, 0, 5, 5, 1, 5, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (3, 4, 0, 11, 2, 2, 1, 6);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (3, 5, 0, 2, 0, 2, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (3, 6, 1, 0, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (3, 7, 1, 1, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (3, 8, 1, 2, 5, 0, 0, 1);

-- Stage 4
INSERT INTO Stage (id, status) VALUES (4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (4, 0, 0, 7, 8, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (4, 1, 0, 2, 7, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (4, 2, 0, 6, 7, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (4, 3, 0, 4, 6, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (4, 4, 0, 0, 4, 2, 2, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (4, 5, 0, 4, 2, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (4, 6, 1, 0, 5, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (4, 7, 1, 1, 5, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (4, 8, 1, 2, 5, 0, 2, 1);

-- Stage 5
INSERT INTO Stage (id, status) VALUES (5, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (5, 0, 0, 0, 6, 2, 1, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (5, 1, 0, 9, 5, 1, 3, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (5, 2, 0, 0, 4, 2, 2, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (5, 3, 0, 5, 2, 1, 3, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (5, 4, 1, 0, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (5, 5, 1, 1, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (5, 6, 1, 2, 5, 0, 2, 1);

-- Stage 6
INSERT INTO Stage (id, status) VALUES (6, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (6, 0, 0, 5, 10, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (6, 1, 0, 2, 8, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (6, 2, 0, 8, 8, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (6, 3, 0, 10, 6, 2, 4, 6);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (6, 4, 0, 5, 5, 1, 5, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (6, 5, 0, 0, 4, 2, 1, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (6, 6, 0, 2, 2, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (6, 7, 0, 8, 2, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (6, 8, 0, 5, 0, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (6, 9, 1, 0, 5, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (6, 10, 1, 1, 5, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (6, 11, 1, 2, 5, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (6, 12, 1, 0, 4, 0, 2, 1);

-- Stage 7
INSERT INTO Stage (id, status) VALUES (7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (7, 0, 0, 2, 11, 2, 1, 4);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (7, 1, 0, 9, 11, 2, 4, 4);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (7, 2, 0, 7, 9, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (7, 3, 0, 10, 8, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (7, 4, 0, 4, 7, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (7, 5, 0, 5, 3, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (7, 6, 1, 0, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (7, 7, 1, 1, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (7, 8, 1, 2, 5, 0, 1, 1);

-- Stage 8
INSERT INTO Stage (id, status) VALUES (8, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (8, 0, 0, 2, 10, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (8, 1, 0, 10, 8, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (8, 2, 0, 0, 4, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (8, 3, 0, 1, 2, 2, 4, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (8, 4, 1, 0, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (8, 5, 1, 1, 5, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (8, 6, 1, 2, 5, 0, 2, 1);

-- Stage 9
INSERT INTO Stage (id, status) VALUES (9, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 0, 0, 1, 11, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 1, 0, 3, 11, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 2, 0, 8, 11, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 3, 0, 11, 11, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 4, 0, 1, 10, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 5, 0, 3, 10, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 6, 0, 8, 10, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 7, 0, 11, 10, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 8, 0, 1, 9, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 9, 0, 3, 9, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 10, 0, 8, 9, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 11, 0, 10, 9, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 12, 0, 11, 9, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 13, 0, 1, 8, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 14, 0, 3, 8, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 15, 0, 5, 8, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 16, 0, 8, 8, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 17, 0, 11, 8, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 18, 0, 1, 7, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 19, 0, 3, 7, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 20, 0, 8, 7, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 21, 0, 11, 7, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 22, 0, 1, 6, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 23, 0, 3, 6, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 24, 0, 8, 6, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 25, 0, 11, 6, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 26, 0, 1, 5, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 27, 0, 3, 5, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 28, 0, 8, 5, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 29, 0, 11, 5, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 30, 0, 1, 4, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 31, 0, 3, 4, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 32, 0, 8, 4, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 33, 0, 11, 4, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 34, 0, 1, 3, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 35, 0, 2, 3, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 36, 0, 3, 3, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 37, 0, 8, 3, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 38, 0, 11, 3, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 39, 0, 1, 2, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 40, 0, 3, 2, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 41, 0, 8, 2, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 42, 0, 11, 2, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 43, 0, 1, 1, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 44, 0, 3, 1, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 45, 0, 8, 1, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 46, 0, 10, 1, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 47, 0, 11, 1, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 48, 0, 0, 0, 2, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 49, 0, 1, 0, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 50, 0, 3, 0, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 51, 0, 8, 0, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 52, 0, 11, 0, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 53, 1, 0, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 54, 1, 1, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 55, 1, 2, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 56, 1, 0, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 57, 1, 1, 4, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (9, 58, 1, 2, 4, 0, 2, 1);

-- Stage 10
INSERT INTO Stage (id, status) VALUES (10, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 0, 0, 0, 11, 2, 1, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 1, 0, 9, 11, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 2, 0, 0, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 3, 0, 1, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 4, 0, 2, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 5, 0, 3, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 6, 0, 4, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 7, 0, 5, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 8, 0, 6, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 9, 0, 7, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 10, 0, 8, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 11, 0, 10, 10, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 12, 0, 2, 9, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 13, 0, 5, 9, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 14, 0, 8, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 15, 0, 2, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 16, 0, 3, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 17, 0, 4, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 18, 0, 5, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 19, 0, 6, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 20, 0, 8, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 21, 0, 2, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 22, 0, 6, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 23, 0, 8, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 24, 0, 1, 6, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 25, 0, 2, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 26, 0, 4, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 27, 0, 6, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 28, 0, 7, 6, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 29, 0, 8, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 30, 0, 2, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 31, 0, 4, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 32, 0, 5, 5, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 33, 0, 6, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 34, 0, 8, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 35, 0, 2, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 36, 0, 4, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 37, 0, 5, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 38, 0, 6, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 39, 0, 8, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 40, 0, 2, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 41, 0, 8, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 42, 0, 2, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 43, 0, 3, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 44, 0, 4, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 45, 0, 5, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 46, 0, 6, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 47, 0, 7, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 48, 0, 8, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 49, 0, 8, 1, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 50, 0, 5, 0, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 51, 1, 0, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 52, 1, 1, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 53, 1, 2, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 54, 1, 0, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 55, 1, 1, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 56, 1, 2, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 57, 1, 0, 3, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 58, 1, 1, 3, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 59, 1, 2, 3, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 60, 1, 0, 2, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 61, 1, 1, 2, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 62, 1, 2, 2, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 63, 1, 0, 1, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 64, 1, 1, 1, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 65, 1, 2, 1, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 66, 1, 0, 0, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 67, 1, 1, 0, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (10, 68, 1, 2, 0, 0, 1, 1);

-- Stage 11
INSERT INTO Stage (id, status) VALUES (11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 0, 0, 2, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 1, 0, 3, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 2, 0, 4, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 3, 0, 5, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 4, 0, 6, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 5, 0, 7, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 6, 0, 8, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 7, 0, 9, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 8, 0, 10, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 9, 0, 2, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 10, 0, 3, 8, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 11, 0, 4, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 12, 0, 5, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 13, 0, 6, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 14, 0, 7, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 15, 0, 8, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 16, 0, 9, 8, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 17, 0, 10, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 18, 0, 2, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 19, 0, 3, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 20, 0, 5, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 21, 0, 6, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 22, 0, 7, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 23, 0, 9, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 24, 0, 10, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 25, 0, 2, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 26, 0, 3, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 27, 0, 4, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 28, 0, 6, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 29, 0, 8, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 30, 0, 9, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 31, 0, 10, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 32, 0, 2, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 33, 0, 3, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 34, 0, 4, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 35, 0, 5, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 36, 0, 7, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 37, 0, 8, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 38, 0, 9, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 39, 0, 10, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 40, 0, 0, 3, 2, 1, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 41, 0, 11, 2, 2, 2, 6);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 42, 1, 0, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 43, 1, 1, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 44, 1, 2, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (11, 45, 1, 0, 4, 0, 1, 1);

-- Stage 12
INSERT INTO Stage (id, status) VALUES (12, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (12, 0, 0, 4, 8, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (12, 1, 0, 11, 8, 2, 2, 6);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (12, 2, 0, 1, 7, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (12, 3, 0, 9, 7, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (12, 4, 0, 1, 4, 2, 1, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (12, 5, 0, 10, 4, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (12, 6, 0, 7, 3, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (12, 7, 0, 4, 2, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (12, 8, 1, 0, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (12, 9, 1, 1, 5, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (12, 10, 1, 2, 5, 0, 2, 1);

-- Stage 13
INSERT INTO Stage (id, status) VALUES (13, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 0, 0, 11, 10, 2, 4, 6);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 1, 0, 0, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 2, 0, 1, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 3, 0, 3, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 4, 0, 4, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 5, 0, 5, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 6, 0, 6, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 7, 0, 7, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 8, 0, 8, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 9, 0, 9, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 10, 0, 10, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 11, 0, 11, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 12, 0, 4, 8, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 13, 0, 2, 7, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 14, 0, 0, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 15, 0, 1, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 16, 0, 2, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 17, 0, 3, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 18, 0, 4, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 19, 0, 5, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 20, 0, 6, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 21, 0, 7, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 22, 0, 8, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 23, 0, 10, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 24, 0, 11, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 25, 0, 6, 4, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 26, 0, 9, 3, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 27, 0, 4, 2, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 28, 0, 6, 2, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 29, 0, 0, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 30, 0, 2, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 31, 0, 3, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 32, 0, 4, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 33, 0, 5, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 34, 0, 6, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 35, 0, 7, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 36, 0, 8, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 37, 0, 9, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 38, 0, 10, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 39, 0, 11, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 40, 0, 11, 0, 2, 1, 6);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 41, 1, 0, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 42, 1, 1, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 43, 1, 2, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 44, 1, 0, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 45, 1, 1, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 46, 1, 2, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 47, 1, 0, 3, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (13, 48, 1, 1, 3, 0, 2, 1);

-- Stage 14
INSERT INTO Stage (id, status) VALUES (14, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 0, 0, 4, 11, 2, 4, 4);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 1, 0, 0, 7, 2, 1, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 2, 0, 4, 7, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 3, 0, 6, 7, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 4, 0, 4, 5, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 5, 0, 6, 5, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 6, 0, 11, 5, 2, 2, 6);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 7, 0, 6, 0, 2, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 8, 1, 0, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 9, 1, 1, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 10, 1, 2, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 11, 1, 0, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 12, 1, 1, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 13, 1, 2, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (14, 14, 1, 0, 3, 0, 1, 1);

-- Stage 15
INSERT INTO Stage (id, status) VALUES (15, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 0, 0, 10, 10, 1, 3, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 1, 0, 1, 8, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 2, 0, 8, 8, 1, 6, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 3, 0, 0, 5, 2, 7, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 4, 0, 4, 5, 0, 6, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 5, 0, 5, 5, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 6, 0, 6, 5, 0, 6, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 7, 0, 8, 5, 0, 6, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 8, 0, 9, 5, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 9, 0, 7, 3, 1, 5, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 10, 0, 2, 2, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 11, 1, 0, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 12, 1, 1, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 13, 1, 2, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 14, 1, 0, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 15, 1, 1, 4, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 16, 1, 2, 4, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 17, 1, 0, 3, 0, 3, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 18, 1, 1, 3, 0, 4, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 19, 1, 2, 3, 0, 5, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (15, 20, 1, 0, 2, 0, 1, 1);

-- Stage 16
INSERT INTO Stage (id, status) VALUES (16, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 0, 0, 5, 11, 2, 1, 4);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 1, 0, 3, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 2, 0, 4, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 3, 0, 6, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 4, 0, 7, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 5, 0, 0, 6, 2, 7, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 6, 0, 3, 6, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 7, 0, 4, 6, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 8, 0, 5, 6, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 9, 0, 6, 6, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 10, 0, 7, 6, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 11, 0, 8, 6, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 12, 0, 9, 6, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 13, 0, 11, 6, 2, 2, 6);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 14, 0, 4, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 15, 0, 6, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 16, 0, 3, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 17, 0, 4, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 18, 0, 6, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 19, 0, 7, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 20, 0, 5, 0, 2, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 21, 1, 0, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 22, 1, 1, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 23, 1, 2, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 24, 1, 0, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 25, 1, 1, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 26, 1, 2, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 27, 1, 0, 3, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 28, 1, 1, 3, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 29, 1, 2, 3, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (16, 30, 1, 0, 2, 0, 1, 1);

-- Stage 17
INSERT INTO Stage (id, status) VALUES (17, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 0, 0, 8, 10, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 1, 0, 7, 9, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 2, 0, 9, 9, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 3, 0, 8, 8, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 4, 0, 3, 7, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 5, 0, 2, 6, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 6, 0, 4, 6, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 7, 0, 3, 5, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 8, 0, 9, 5, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 9, 0, 8, 4, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 10, 0, 10, 4, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 11, 0, 9, 3, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 12, 0, 6, 0, 2, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 13, 1, 0, 5, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 14, 1, 1, 5, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 15, 1, 2, 5, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 16, 1, 0, 4, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 17, 1, 1, 4, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 18, 1, 2, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 19, 1, 0, 3, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 20, 1, 1, 3, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 21, 1, 2, 3, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 22, 1, 0, 2, 0, 3, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 23, 1, 1, 2, 0, 4, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (17, 24, 1, 2, 2, 0, 5, 1);

-- Stage 18
INSERT INTO Stage (id, status) VALUES (18, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 0, 0, 5, 11, 2, 7, 4);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 1, 0, 7, 10, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 2, 0, 1, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 3, 0, 2, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 4, 0, 3, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 5, 0, 4, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 6, 0, 6, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 7, 0, 7, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 8, 0, 8, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 9, 0, 9, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 10, 0, 4, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 11, 0, 6, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 12, 0, 7, 7, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 13, 0, 8, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 14, 0, 9, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 15, 0, 4, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 16, 0, 5, 6, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 17, 0, 6, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 18, 0, 4, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 19, 0, 6, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 20, 0, 8, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 21, 0, 9, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 22, 0, 1, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 23, 0, 2, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 24, 0, 3, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 25, 0, 4, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 26, 0, 6, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 27, 0, 7, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 28, 0, 8, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 29, 0, 9, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 30, 0, 1, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 31, 0, 2, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 32, 0, 3, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 33, 0, 7, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 34, 0, 8, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 35, 0, 9, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 36, 0, 1, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 37, 0, 2, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 38, 0, 4, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 39, 0, 6, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 40, 0, 8, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 41, 0, 9, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 42, 0, 1, 0, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 43, 0, 2, 0, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 44, 0, 3, 0, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 45, 0, 4, 0, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 46, 0, 5, 0, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 47, 0, 6, 0, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 48, 0, 7, 0, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 49, 0, 8, 0, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 50, 0, 9, 0, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 51, 1, 0, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 52, 1, 1, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 53, 1, 2, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 54, 1, 0, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 55, 1, 1, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (18, 56, 1, 2, 4, 0, 9, 1);

-- Stage 19
INSERT INTO Stage (id, status) VALUES (19, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (19, 0, 0, 4, 10, 2, 4, 4);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (19, 1, 0, 6, 9, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (19, 2, 0, 1, 7, 2, 1, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (19, 3, 0, 8, 7, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (19, 4, 0, 8, 4, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (19, 5, 0, 4, 3, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (19, 6, 1, 0, 5, 0, 9, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (19, 7, 1, 1, 5, 0, 9, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (19, 8, 1, 2, 5, 0, 2, 1);

-- Stage 20
INSERT INTO Stage (id, status) VALUES (20, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 0, 0, 8, 11, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 1, 0, 9, 11, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 2, 0, 10, 11, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 3, 0, 11, 11, 2, 2, 5);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 4, 0, 0, 10, 2, 4, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 5, 0, 6, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 6, 0, 7, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 7, 0, 8, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 8, 0, 11, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 9, 0, 11, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 10, 0, 8, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 11, 0, 10, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 12, 0, 11, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 13, 0, 6, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 14, 0, 10, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 15, 0, 3, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 16, 0, 7, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 17, 0, 10, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 18, 0, 3, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 19, 0, 3, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 20, 0, 2, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 21, 0, 4, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 22, 0, 5, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 23, 0, 6, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 24, 0, 0, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 25, 0, 1, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 26, 0, 3, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 27, 0, 0, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 28, 0, 1, 1, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 29, 0, 2, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 30, 0, 0, 0, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 31, 0, 1, 0, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 32, 0, 2, 0, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 33, 0, 11, 0, 2, 1, 7);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 34, 1, 0, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 35, 1, 1, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 36, 1, 2, 5, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 37, 1, 0, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 38, 1, 1, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 39, 1, 2, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 40, 1, 0, 3, 0, 9, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (20, 41, 1, 1, 3, 0, 0, 1);

-- Stage 21
INSERT INTO Stage (id, status) VALUES (21, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 0, 0, 1, 11, 1, 6, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 1, 0, 4, 11, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 2, 0, 6, 11, 1, 6, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 3, 0, 8, 11, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 4, 0, 4, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 5, 0, 8, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 6, 0, 4, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 7, 0, 8, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 8, 0, 0, 6, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 9, 0, 4, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 10, 0, 8, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 11, 0, 11, 5, 2, 7, 6);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 12, 0, 0, 3, 2, 7, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 13, 0, 4, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 14, 0, 8, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 15, 0, 4, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 16, 0, 8, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 17, 0, 10, 0, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 18, 1, 0, 5, 0, 9, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 19, 1, 1, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 20, 1, 2, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 21, 1, 0, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (21, 22, 1, 1, 4, 0, 1, 1);

-- Stage 22
INSERT INTO Stage (id, status) VALUES (22, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 0, 0, 0, 11, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 1, 0, 1, 11, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 2, 0, 2, 11, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 3, 0, 3, 11, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 4, 0, 4, 11, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 5, 0, 8, 11, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 6, 0, 0, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 7, 0, 2, 10, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 8, 0, 3, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 9, 0, 5, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 10, 0, 6, 10, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 11, 0, 7, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 12, 0, 8, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 13, 0, 0, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 14, 0, 2, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 15, 0, 3, 9, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 16, 0, 4, 9, 0, 6, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 17, 0, 5, 9, 0, 6, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 18, 0, 6, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 19, 0, 7, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 20, 0, 8, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 21, 0, 0, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 22, 0, 1, 8, 1, 7, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 23, 0, 3, 8, 0, 6, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 24, 0, 5, 8, 0, 6, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 25, 0, 11, 8, 2, 1, 6);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 26, 0, 0, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 27, 0, 1, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 28, 0, 2, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 29, 0, 3, 7, 0, 6, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 30, 0, 4, 7, 0, 6, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 31, 0, 5, 7, 0, 6, 3);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 32, 0, 6, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 33, 0, 7, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 34, 0, 8, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 35, 0, 0, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 36, 0, 3, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 37, 0, 5, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 38, 0, 8, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 39, 0, 0, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 40, 0, 3, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 41, 0, 5, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 42, 0, 8, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 43, 0, 1, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 44, 0, 2, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 45, 0, 3, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 46, 0, 5, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 47, 0, 6, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 48, 0, 7, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 49, 0, 0, 2, 2, 4, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 50, 0, 4, 0, 2, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 51, 1, 0, 5, 0, 9, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 52, 1, 1, 5, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 53, 1, 2, 5, 0, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 54, 1, 0, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 55, 1, 1, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 56, 1, 2, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 57, 1, 0, 3, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (22, 58, 1, 1, 3, 0, 0, 1);

-- Stage 23
INSERT INTO Stage (id, status) VALUES (23, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 0, 0, 3, 8, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 1, 0, 9, 8, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 2, 0, 4, 7, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 3, 0, 8, 7, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 4, 0, 5, 6, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 5, 0, 7, 6, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 6, 0, 0, 5, 2, 2, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 7, 0, 4, 3, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 8, 0, 6, 3, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 9, 0, 3, 2, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 10, 0, 7, 2, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 11, 1, 0, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 12, 1, 1, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 13, 1, 2, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 14, 1, 0, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 15, 1, 1, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 16, 1, 2, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 17, 1, 0, 3, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 18, 1, 1, 3, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 19, 1, 2, 3, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 20, 1, 0, 2, 0, 7, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (23, 21, 1, 1, 2, 0, 7, 1);

-- Stage 24
INSERT INTO Stage (id, status) VALUES (24, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 0, 0, 7, 10, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 1, 0, 5, 9, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 2, 0, 10, 9, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 3, 0, 1, 8, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 4, 0, 4, 7, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 5, 0, 0, 5, 2, 1, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 6, 0, 7, 5, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 7, 0, 8, 5, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 8, 0, 4, 4, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 9, 0, 5, 2, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 10, 1, 0, 5, 0, 7, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 11, 1, 1, 5, 0, 7, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 12, 1, 2, 5, 0, 7, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 13, 1, 0, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 14, 1, 1, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 15, 1, 2, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 16, 1, 0, 3, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 17, 1, 1, 3, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 18, 1, 2, 3, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (24, 19, 1, 0, 2, 0, 1, 1);

-- Stage 25
INSERT INTO Stage (id, status) VALUES (25, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 0, 0, 3, 11, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 1, 0, 4, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 2, 0, 8, 10, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 3, 0, 2, 9, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 4, 0, 4, 9, 1, 4, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 5, 0, 8, 9, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 6, 0, 8, 8, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 7, 0, 8, 7, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 8, 0, 0, 6, 2, 1, 2);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 9, 0, 2, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 10, 0, 8, 6, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 11, 0, 11, 6, 2, 4, 6);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 12, 0, 2, 5, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 13, 0, 2, 4, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 14, 0, 2, 3, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 15, 0, 6, 3, 1, 1, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 16, 0, 8, 3, 1, 2, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 17, 0, 2, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 18, 0, 8, 2, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 19, 0, 9, 1, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 20, 0, 10, 0, 0, 11, 0);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 21, 1, 0, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 22, 1, 1, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 23, 1, 2, 5, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 24, 1, 0, 4, 0, 0, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 25, 1, 1, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 26, 1, 2, 4, 0, 1, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 27, 1, 0, 3, 0, 7, 1);
INSERT INTO StageDefinition (stageid, itemid, panel, positionX, positionY, item, type, direction) VALUES (25, 28, 1, 1, 3, 0, 7, 1);

